print-status: False

api:
    database:
        dialect: ${DATABASE_DIALECT:sqlite}
        settings:
            check_same_thread: False

swagger:
    schemes: [https]
    host: ${:DEVELOPMENT_HOST}
